# -*- coding: utf-8 -*-
"""14_my_module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1APUy9L4Yl30svCy2nSUh_et7fHlgRr5W
"""

### Módulo para pruebas ###

def sumValue(numberOne, numberTwo, numberThree):
    print(numberOne + numberTwo + numberThree)


def printValue(value):
    print(value)